server:
  port: 8080

spring:
  application:
    name: schedule-api
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/theater_schedule
    username: postgres
    password: 19198076Ru

app:
  jwt:
    # Key for HS512 algorithm
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 100
  cors:
    allowed-origins: http://localhost:3000
